routes:
/:
  data: page.home
  template: home
/sign-up/:
  template: sign-up
collections:
  /blog/:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
