routes:
  /: home
  /sign-up/: sign-up
  /code-of-conduct/: code-of-conduct
  /about/: about
collections:
  /blog/:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
